name: OpenFaaS Terraform CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: .

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: .

    - name: Wait for demo
      run: sleep 60

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: .
